builds:
  - main: proteus-orchestrate/main.go
    binary: proteus-orchestrate
    goos:
      - darwin
      - linux
    goarch:
      - amd64
  - main: proteus-registry/main.go
    binary: proteus-registry
    goos:
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
