builds:
  - main: orchestrate/main.go
    binary: ooni-orchestrate
    goos:
      - darwin
      - linux
    goarch:
      - amd64
  - main: registry/main.go
    binary: ooni-registry
    goos:
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  files:
    - LICENSE
# This doesn't actually work, though it's documented to work:
# https://goreleaser.com/#checksum
#checksum:
#  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
