language: go
go:
  - 1.8.5
  # XXX temporarily disabled, because tip produces inconsistent go fmt results
  #- tip
install:
  # Rename TheTorProject to all lowercase to make imports work properly
  - cd $GOPATH/src/github.com/ooni/orchestra
  # Install govendor
  - make vendor
script:
  - make check
  - make lint
