[core]
environment = "development"
log-level = "debug"
gorush-url = "http://localhost:8081"
notify-topic-ios = "org.openobservatory.NetProbe"
notify-click-action-android = "org.openobservatory.ooniprobe.OPEN_BROWSER"

[auth]
jwt-secret = "TESTING"
gorush-basic-auth-user = "{{ proteus_notify_basic_auth_user }}"
gorush-basic-auth-password = "{{ proteus_notify_basic_auth_password }}"

[api]
port = 8082
address = "127.0.0.1"
default-inputs-to-return = 10

[database]
url = "postgres://proteus:changeme@127.0.0.1:32768/proteus?sslmode=disable"

[operator]
private-key = "ooni-orchestrate.priv"
public-key = "ooni-orchestrate.pub"
pkcs11-lib-path = "/usr/local/lib/libykcs11.dylib"
token-serial = "1234"
user-pin = "424242"
so-pin = "424242"
