[core]
environment = "development"
log-level = "debug"
gorush-url = "http://gorush:8081"
notify-topic-ios = "org.openobservatory.NetProbe"
notify-click-action-android = "org.openobservatory.ooniprobe.OPEN_BROWSER"

[auth]
jwt-secret = "CHANGEME"
gorush-basic-auth-user = "orchestra"
gorush-basic-auth-password = "changeme"

[api]
port = 8082
address = "0.0.0.0"
default-inputs-to-return = 10

[database]
url = "postgres://orchestra:changeme@db/orchestra?sslmode=disable"
